export * from './adminController.service';
import { AdminControllerService } from './adminController.service';
export * from './deliveryController.service';
import { DeliveryControllerService } from './deliveryController.service';
export * from './demoController.service';
import { DemoControllerService } from './demoController.service';
export * from './followingController.service';
import { FollowingControllerService } from './followingController.service';
export * from './imageController.service';
import { ImageControllerService } from './imageController.service';
export * from './messageController.service';
import { MessageControllerService } from './messageController.service';
export * from './offerController.service';
import { OfferControllerService } from './offerController.service';
export * from './orderController.service';
import { OrderControllerService } from './orderController.service';
export * from './paymentMethodController.service';
import { PaymentMethodControllerService } from './paymentMethodController.service';
export * from './productController.service';
import { ProductControllerService } from './productController.service';
export * from './reportController.service';
import { ReportControllerService } from './reportController.service';
export * from './reviewController.service';
import { ReviewControllerService } from './reviewController.service';
export * from './superAdminController.service';
import { SuperAdminControllerService } from './superAdminController.service';
export * from './transactionController.service';
import { TransactionControllerService } from './transactionController.service';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export const APIS = [AdminControllerService, DeliveryControllerService, DemoControllerService, FollowingControllerService, ImageControllerService, MessageControllerService, OfferControllerService, OrderControllerService, PaymentMethodControllerService, ProductControllerService, ReportControllerService, ReviewControllerService, SuperAdminControllerService, TransactionControllerService, UserControllerService];
