export * from './deliveryController.service';
import { DeliveryControllerService } from './deliveryController.service';
export * from './messageController.service';
import { MessageControllerService } from './messageController.service';
export * from './offerController.service';
import { OfferControllerService } from './offerController.service';
export * from './orderController.service';
import { OrderControllerService } from './orderController.service';
export * from './paymentMethodController.service';
import { PaymentMethodControllerService } from './paymentMethodController.service';
export * from './productController.service';
import { ProductControllerService } from './productController.service';
export * from './reviewController.service';
import { ReviewControllerService } from './reviewController.service';
export * from './transactionController.service';
import { TransactionControllerService } from './transactionController.service';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export const APIS = [DeliveryControllerService, MessageControllerService, OfferControllerService, OrderControllerService, PaymentMethodControllerService, ProductControllerService, ReviewControllerService, TransactionControllerService, UserControllerService];
