/**
 * Country State City API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: gadadarshan@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface City { 
    id?: number;
    name?: string;
    stateId?: number;
    stateCode?: string;
    countryId?: number;
    countryCode?: string;
    latitude?: string;
    longitude?: string;
}