/**
 * Country State City API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: gadadarshan@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Country { 
    id?: number;
    name?: string;
    iso3?: string;
    iso2?: string;
    phonecode?: string;
    capital?: string;
    currency?: string;
    _native?: string;
    emoji?: string;
    emojiU?: string;
}