/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CustomMoneyDTO } from './customMoneyDTO';
import { ProductCategoryDTO } from './productCategoryDTO';
import { ProductDTO } from './productDTO';
import { SizeDTO } from './sizeDTO';
import { UserBasicDTO } from './userBasicDTO';

export interface ClothingDTO extends ProductDTO { 
    productGender: ClothingDTO.ProductGenderEnum;
    clothingSize: SizeDTO;
    colour: ClothingDTO.ColourEnum;
}
export namespace ClothingDTO {
    export type ProductGenderEnum = 'MALE' | 'FEMALE' | 'UNISEX';
    export const ProductGenderEnum = {
        MALE: 'MALE' as ProductGenderEnum,
        FEMALE: 'FEMALE' as ProductGenderEnum,
        UNISEX: 'UNISEX' as ProductGenderEnum
    };
    export type ColourEnum = 'YELLOW' | 'GREEN' | 'BLUE' | 'RED' | 'BLACK' | 'WHITE' | 'MULTICOLOUR';
    export const ColourEnum = {
        YELLOW: 'YELLOW' as ColourEnum,
        GREEN: 'GREEN' as ColourEnum,
        BLUE: 'BLUE' as ColourEnum,
        RED: 'RED' as ColourEnum,
        BLACK: 'BLACK' as ColourEnum,
        WHITE: 'WHITE' as ColourEnum,
        MULTICOLOUR: 'MULTICOLOUR' as ColourEnum
    };
}