/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';
import { CustomMoney } from './customMoney';
import { Order } from './order';

export interface Delivery { 
    id?: string;
    order?: Order;
    sendTime?: Date;
    deliveredTime?: Date;
    deliveryCost?: CustomMoney;
    shipper?: string;
    deliveryStatus?: Delivery.DeliveryStatusEnum;
    senderAddress?: Address;
    receiverAddress?: Address;
}
export namespace Delivery {
    export type DeliveryStatusEnum = 'SHIPPED' | 'DELIVERED';
    export const DeliveryStatusEnum = {
        SHIPPED: 'SHIPPED' as DeliveryStatusEnum,
        DELIVERED: 'DELIVERED' as DeliveryStatusEnum
    };
}