/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';
import { Money } from './money';
import { OrderDTO } from './orderDTO';

export interface DeliveryDTO { 
    order?: OrderDTO;
    deliveryCost?: Money;
    shipper?: string;
    senderAddress?: Address;
    receiverAddress?: Address;
    id?: string;
}