/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressDTO } from './addressDTO';
import { CustomMoneyDTO } from './customMoneyDTO';

export interface DeliveryDTO { 
    sendTime: Date;
    deliveredTime?: Date;
    deliveryCost?: CustomMoneyDTO;
    shipper?: string;
    deliveryStatus: DeliveryDTO.DeliveryStatusEnum;
    senderAddress: AddressDTO;
    receiverAddress: AddressDTO;
    id?: string;
}
export namespace DeliveryDTO {
    export type DeliveryStatusEnum = 'SHIPPED' | 'DELIVERED';
    export const DeliveryStatusEnum = {
        SHIPPED: 'SHIPPED' as DeliveryStatusEnum,
        DELIVERED: 'DELIVERED' as DeliveryStatusEnum
    };
}