/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressDTO } from './addressDTO';
import { MessageDTO } from './messageDTO';
import { MyMoney } from './myMoney';
import { OrderDTO } from './orderDTO';
import { ProductDTO } from './productDTO';
import { UserDTO } from './userDTO';

export interface EntertainmentDTO extends ProductDTO { 
    entertainmentType?: EntertainmentDTO.EntertainmentTypeEnum;
}
export namespace EntertainmentDTO {
    export type EntertainmentTypeEnum = 'VIDEOGAMES_CONSOLES_XBOXONE' | 'VIDEOGAMES_CONSOLES_PLAYSTATION_FIVE' | 'VIDEOGAMES_CONSOLES_PLAYSTATION_OLDER' | 'VIDEOGAMES_CONSOLES_PCGAMES' | 'MEDIA_MUSIC' | 'MEDIA_VIDEO' | 'BOOKS_NON_FICTION' | 'BOOKS_KIDS' | 'BOOKS_LITERATURE' | 'BOOKS_FICTION';
    export const EntertainmentTypeEnum = {
        VIDEOGAMESCONSOLESXBOXONE: 'VIDEOGAMES_CONSOLES_XBOXONE' as EntertainmentTypeEnum,
        VIDEOGAMESCONSOLESPLAYSTATIONFIVE: 'VIDEOGAMES_CONSOLES_PLAYSTATION_FIVE' as EntertainmentTypeEnum,
        VIDEOGAMESCONSOLESPLAYSTATIONOLDER: 'VIDEOGAMES_CONSOLES_PLAYSTATION_OLDER' as EntertainmentTypeEnum,
        VIDEOGAMESCONSOLESPCGAMES: 'VIDEOGAMES_CONSOLES_PCGAMES' as EntertainmentTypeEnum,
        MEDIAMUSIC: 'MEDIA_MUSIC' as EntertainmentTypeEnum,
        MEDIAVIDEO: 'MEDIA_VIDEO' as EntertainmentTypeEnum,
        BOOKSNONFICTION: 'BOOKS_NON_FICTION' as EntertainmentTypeEnum,
        BOOKSKIDS: 'BOOKS_KIDS' as EntertainmentTypeEnum,
        BOOKSLITERATURE: 'BOOKS_LITERATURE' as EntertainmentTypeEnum,
        BOOKSFICTION: 'BOOKS_FICTION' as EntertainmentTypeEnum
    };
}