/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CustomMoneyDTO } from './customMoneyDTO';
import { ProductCategoryDTO } from './productCategoryDTO';
import { ProductCreateDTO } from './productCreateDTO';

export interface EntertainmentCreateDTO extends ProductCreateDTO { 
    entertainmentLanguage: EntertainmentCreateDTO.EntertainmentLanguageEnum;
}
export namespace EntertainmentCreateDTO {
    export type EntertainmentLanguageEnum = 'MULTI_LANGUAGE' | 'ITALIAN' | 'FRENCH' | 'GERMAN' | 'ENGLISH' | 'SPANISH' | 'OTHERS';
    export const EntertainmentLanguageEnum = {
        MULTILANGUAGE: 'MULTI_LANGUAGE' as EntertainmentLanguageEnum,
        ITALIAN: 'ITALIAN' as EntertainmentLanguageEnum,
        FRENCH: 'FRENCH' as EntertainmentLanguageEnum,
        GERMAN: 'GERMAN' as EntertainmentLanguageEnum,
        ENGLISH: 'ENGLISH' as EntertainmentLanguageEnum,
        SPANISH: 'SPANISH' as EntertainmentLanguageEnum,
        OTHERS: 'OTHERS' as EntertainmentLanguageEnum
    };
}