/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressDTO } from './addressDTO';
import { MessageDTO } from './messageDTO';
import { MyMoney } from './myMoney';
import { OrderDTO } from './orderDTO';
import { ProductDTO } from './productDTO';
import { UserDTO } from './userDTO';

export interface HomeDTO extends ProductDTO { 
    colour?: HomeDTO.ColourEnum;
    homeType?: HomeDTO.HomeTypeEnum;
}
export namespace HomeDTO {
    export type ColourEnum = 'YELLOW' | 'GREEN' | 'BLUE' | 'RED' | 'BLACK' | 'WHITE' | 'MULTICOLOUR';
    export const ColourEnum = {
        YELLOW: 'YELLOW' as ColourEnum,
        GREEN: 'GREEN' as ColourEnum,
        BLUE: 'BLUE' as ColourEnum,
        RED: 'RED' as ColourEnum,
        BLACK: 'BLACK' as ColourEnum,
        WHITE: 'WHITE' as ColourEnum,
        MULTICOLOUR: 'MULTICOLOUR' as ColourEnum
    };
    export type HomeTypeEnum = 'TEXTILES_BLANKETS' | 'TEXTILES_CUSHIONS' | 'TEXTILES_TABLE_LINEN' | 'TEXTILES_TOWEL' | 'TEXTILES_BEDDING' | 'HOME_ACCESSORIES_COOKS' | 'HOME_ACCESSORIES_PICTURE' | 'HOME_ACCESSORIES_PHOTO_FRAMES' | 'HOME_ACCESSORIES_STORAGE' | 'HOME_ACCESSORIES_MIRRORS' | 'HOME_ACCESSORIES_VASES' | 'TABLEWARE_DINNERWARE' | 'TABLEWARE_CUTLERY' | 'TABLEWARE_DRINKWARE';
    export const HomeTypeEnum = {
        TEXTILESBLANKETS: 'TEXTILES_BLANKETS' as HomeTypeEnum,
        TEXTILESCUSHIONS: 'TEXTILES_CUSHIONS' as HomeTypeEnum,
        TEXTILESTABLELINEN: 'TEXTILES_TABLE_LINEN' as HomeTypeEnum,
        TEXTILESTOWEL: 'TEXTILES_TOWEL' as HomeTypeEnum,
        TEXTILESBEDDING: 'TEXTILES_BEDDING' as HomeTypeEnum,
        HOMEACCESSORIESCOOKS: 'HOME_ACCESSORIES_COOKS' as HomeTypeEnum,
        HOMEACCESSORIESPICTURE: 'HOME_ACCESSORIES_PICTURE' as HomeTypeEnum,
        HOMEACCESSORIESPHOTOFRAMES: 'HOME_ACCESSORIES_PHOTO_FRAMES' as HomeTypeEnum,
        HOMEACCESSORIESSTORAGE: 'HOME_ACCESSORIES_STORAGE' as HomeTypeEnum,
        HOMEACCESSORIESMIRRORS: 'HOME_ACCESSORIES_MIRRORS' as HomeTypeEnum,
        HOMEACCESSORIESVASES: 'HOME_ACCESSORIES_VASES' as HomeTypeEnum,
        TABLEWAREDINNERWARE: 'TABLEWARE_DINNERWARE' as HomeTypeEnum,
        TABLEWARECUTLERY: 'TABLEWARE_CUTLERY' as HomeTypeEnum,
        TABLEWAREDRINKWARE: 'TABLEWARE_DRINKWARE' as HomeTypeEnum
    };
}