/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CustomMoneyDTO } from './customMoneyDTO';
import { ProductCategoryDTO } from './productCategoryDTO';
import { ProductCreateDTO } from './productCreateDTO';
import { SizeDTO } from './sizeDTO';

export interface HomeCreateDTO extends ProductCreateDTO { 
    colour: HomeCreateDTO.ColourEnum;
    homeSize: SizeDTO;
    homeMaterial: HomeCreateDTO.HomeMaterialEnum;
}
export namespace HomeCreateDTO {
    export type ColourEnum = 'YELLOW' | 'GREEN' | 'BLUE' | 'RED' | 'BLACK' | 'WHITE' | 'MULTICOLOUR';
    export const ColourEnum = {
        YELLOW: 'YELLOW' as ColourEnum,
        GREEN: 'GREEN' as ColourEnum,
        BLUE: 'BLUE' as ColourEnum,
        RED: 'RED' as ColourEnum,
        BLACK: 'BLACK' as ColourEnum,
        WHITE: 'WHITE' as ColourEnum,
        MULTICOLOUR: 'MULTICOLOUR' as ColourEnum
    };
    export type HomeMaterialEnum = 'Cotton' | 'Linen' | 'Wool' | 'Acrylic' | 'Chiffon' | 'Polyamide_Nylon' | 'Polyester' | 'Silk' | 'Ceramic' | 'Glass' | 'Stainless_Steel' | 'Plastic' | 'Wood' | 'Stone' | 'Porcelain' | 'Silver' | 'Metal' | 'Other';
    export const HomeMaterialEnum = {
        Cotton: 'Cotton' as HomeMaterialEnum,
        Linen: 'Linen' as HomeMaterialEnum,
        Wool: 'Wool' as HomeMaterialEnum,
        Acrylic: 'Acrylic' as HomeMaterialEnum,
        Chiffon: 'Chiffon' as HomeMaterialEnum,
        PolyamideNylon: 'Polyamide_Nylon' as HomeMaterialEnum,
        Polyester: 'Polyester' as HomeMaterialEnum,
        Silk: 'Silk' as HomeMaterialEnum,
        Ceramic: 'Ceramic' as HomeMaterialEnum,
        Glass: 'Glass' as HomeMaterialEnum,
        StainlessSteel: 'Stainless_Steel' as HomeMaterialEnum,
        Plastic: 'Plastic' as HomeMaterialEnum,
        Wood: 'Wood' as HomeMaterialEnum,
        Stone: 'Stone' as HomeMaterialEnum,
        Porcelain: 'Porcelain' as HomeMaterialEnum,
        Silver: 'Silver' as HomeMaterialEnum,
        Metal: 'Metal' as HomeMaterialEnum,
        Other: 'Other' as HomeMaterialEnum
    };
}