/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface HttpStatusCode { 
    error?: boolean;
    is4xxClientError?: boolean;
    is5xxServerError?: boolean;
    is1xxInformational?: boolean;
    is2xxSuccessful?: boolean;
    is3xxRedirection?: boolean;
}