/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface HttpHeadersContentLanguage { 
    language?: string;
    displayName?: string;
    country?: string;
    variant?: string;
    script?: string;
    unicodeLocaleAttributes?: Array<string>;
    unicodeLocaleKeys?: Array<string>;
    displayLanguage?: string;
    displayScript?: string;
    displayCountry?: string;
    displayVariant?: string;
    extensionKeys?: Array<string>;
    iso3Language?: string;
    iso3Country?: string;
}