/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CurrencyUnit } from './currencyUnit';

export interface Money { 
    zero?: boolean;
    negative?: boolean;
    positive?: boolean;
    amount?: number;
    scale?: number;
    amountMinorLong?: number;
    amountMajorLong?: number;
    positiveOrZero?: boolean;
    currencyUnit?: CurrencyUnit;
    amountMajorInt?: number;
    minorPart?: number;
    amountMajor?: number;
    amountMinorInt?: number;
    negativeOrZero?: boolean;
    amountMinor?: number;
}