/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CustomMoney } from './customMoney';
import { Message } from './message';
import { Order } from './order';
import { Product } from './product';
import { User } from './user';

export interface Offer { 
    id?: string;
    amount?: CustomMoney;
    creationTime?: Date;
    state?: Offer.StateEnum;
    offerer?: User;
    product?: Product;
    message?: Message;
    order?: Order;
}
export namespace Offer {
    export type StateEnum = 'PENDING' | 'ACCEPTED' | 'REJECTED' | 'CANCELLED';
    export const StateEnum = {
        PENDING: 'PENDING' as StateEnum,
        ACCEPTED: 'ACCEPTED' as StateEnum,
        REJECTED: 'REJECTED' as StateEnum,
        CANCELLED: 'CANCELLED' as StateEnum
    };
}