/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressDTO } from './addressDTO';
import { OfferBasicDTO } from './offerBasicDTO';
import { ProductBasicDTO } from './productBasicDTO';

export interface OrderCreateDTO { 
    product: ProductBasicDTO;
    offer?: OfferBasicDTO;
    deliveryAddress: AddressDTO;
}