/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OfferBasicDTO } from './offerBasicDTO';
import { ProductBasicDTO } from './productBasicDTO';

export interface OrderBasicDTO { 
    id: string;
    state: OrderBasicDTO.StateEnum;
    orderDate?: Date;
    orderUpdateDate?: Date;
    product: ProductBasicDTO;
    offer?: OfferBasicDTO;
}
export namespace OrderBasicDTO {
    export type StateEnum = 'CANCELED' | 'PENDING' | 'PURCHASED' | 'SHIPPED' | 'DELIVERED' | 'COMPLETED' | 'REVIEWED';
    export const StateEnum = {
        CANCELED: 'CANCELED' as StateEnum,
        PENDING: 'PENDING' as StateEnum,
        PURCHASED: 'PURCHASED' as StateEnum,
        SHIPPED: 'SHIPPED' as StateEnum,
        DELIVERED: 'DELIVERED' as StateEnum,
        COMPLETED: 'COMPLETED' as StateEnum,
        REVIEWED: 'REVIEWED' as StateEnum
    };
}