/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CustomMoneyDTO } from './customMoneyDTO';
import { ProductImageDTO } from './productImageDTO';
import { UserBasicDTO } from './userBasicDTO';

export interface ProductBasicDTO { 
    id?: string;
    title?: string;
    description?: string;
    uploadDate?: Date;
    productCost: CustomMoneyDTO;
    deliveryCost: CustomMoneyDTO;
    brand?: string;
    condition?: ProductBasicDTO.ConditionEnum;
    likesNumber?: number;
    seller?: UserBasicDTO;
    productImages?: ProductImageDTO;
    productCategory?: ProductBasicDTO.ProductCategoryEnum;
}
export namespace ProductBasicDTO {
    export type ConditionEnum = 'NEW_WITH_TAG' | 'NEW_WITHOUT_TAG' | 'VERY_GOOD' | 'GOOD' | 'ACCEPTABLE';
    export const ConditionEnum = {
        NEWWITHTAG: 'NEW_WITH_TAG' as ConditionEnum,
        NEWWITHOUTTAG: 'NEW_WITHOUT_TAG' as ConditionEnum,
        VERYGOOD: 'VERY_GOOD' as ConditionEnum,
        GOOD: 'GOOD' as ConditionEnum,
        ACCEPTABLE: 'ACCEPTABLE' as ConditionEnum
    };
    export type ProductCategoryEnum = 'OTHER' | 'ENTERTAINMENT' | 'HOME' | 'CLOTHING';
    export const ProductCategoryEnum = {
        OTHER: 'OTHER' as ProductCategoryEnum,
        ENTERTAINMENT: 'ENTERTAINMENT' as ProductCategoryEnum,
        HOME: 'HOME' as ProductCategoryEnum,
        CLOTHING: 'CLOTHING' as ProductCategoryEnum
    };
}