/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProductBasicDTO } from './productBasicDTO';
import { UserBasicDTO } from './userBasicDTO';

export interface ReportDTO { 
    id?: string;
    reporterUser?: UserBasicDTO;
    description?: string;
    reportedUser?: UserBasicDTO;
    reportedProduct?: ProductBasicDTO;
    date?: Date;
    status?: ReportDTO.StatusEnum;
}
export namespace ReportDTO {
    export type StatusEnum = 'PENDING' | 'CLOSED';
    export const StatusEnum = {
        PENDING: 'PENDING' as StatusEnum,
        CLOSED: 'CLOSED' as StatusEnum
    };
}