/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HttpHeaders } from './httpHeaders';
import { HttpStatusCode } from './httpStatusCode';
import { ProblemDetail } from './problemDetail';
import { ResponseStatusExceptionCause } from './responseStatusExceptionCause';
import { ResponseStatusExceptionCauseStackTrace } from './responseStatusExceptionCauseStackTrace';
import { ResponseStatusExceptionCauseSuppressed } from './responseStatusExceptionCauseSuppressed';
import { ResponseStatusExceptionHeaders } from './responseStatusExceptionHeaders';
import { ResponseStatusExceptionRootCause } from './responseStatusExceptionRootCause';

export interface ResponseStatusException { 
    cause?: ResponseStatusExceptionCause;
    stackTrace?: Array<ResponseStatusExceptionCauseStackTrace>;
    headers?: ResponseStatusExceptionHeaders;
    body?: ProblemDetail;
    reason?: string;
    message?: string;
    responseHeaders?: HttpHeaders;
    instance?: string;
    statusCode?: HttpStatusCode;
    detail?: string;
    title?: string;
    detailMessageArguments?: Array<any>;
    detailMessageCode?: string;
    type?: string;
    titleMessageCode?: string;
    rootCause?: ResponseStatusExceptionRootCause;
    mostSpecificCause?: ResponseStatusExceptionCause;
    suppressed?: Array<ResponseStatusExceptionCauseSuppressed>;
    localizedMessage?: string;
}