/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CustomMoneyDTO } from './customMoneyDTO';

export interface TransactionDTO { 
    id: string;
    creationTime?: Date;
    amount: CustomMoneyDTO;
    transactionState: TransactionDTO.TransactionStateEnum;
    paymentMethod: string;
    paymentMethodOwner: string;
}
export namespace TransactionDTO {
    export type TransactionStateEnum = 'REJECTED' | 'COMPLETED';
    export const TransactionStateEnum = {
        REJECTED: 'REJECTED' as TransactionStateEnum,
        COMPLETED: 'COMPLETED' as TransactionStateEnum
    };
}