/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressDTO } from './addressDTO';
import { ClothingDTO } from './clothingDTO';
import { EntertainmentDTO } from './entertainmentDTO';
import { HomeDTO } from './homeDTO';
import { MessageDTO } from './messageDTO';
import { OfferDTO } from './offerDTO';
import { OrderDTO } from './orderDTO';
import { PaymentMethodDTO } from './paymentMethodDTO';
import { ProductDTO } from './productDTO';
import { ReviewDTO } from './reviewDTO';

export interface UserDTO { 
    id?: string;
    username: string;
    password?: string;
    email?: string;
    photo?: Array<string>;
    provider: UserDTO.ProviderEnum;
    address?: AddressDTO;
    role: UserDTO.RoleEnum;
    defaultPaymentMethod?: PaymentMethodDTO;
    paymentMethods?: Array<PaymentMethodDTO>;
    offers?: Array<OfferDTO>;
    followers?: Array<UserDTO>;
    soldProducts?: Array<ProductDTO | ClothingDTO | EntertainmentDTO | HomeDTO>;
    follows?: Array<UserDTO>;
    likes?: Array<ProductDTO | ClothingDTO | EntertainmentDTO | HomeDTO>;
    sendMessages?: Array<MessageDTO>;
    receivedMessages?: Array<MessageDTO>;
    orders?: Array<OrderDTO>;
    receivedReviews?: Array<ReviewDTO>;
    sentReviews?: Array<ReviewDTO>;
}
export namespace UserDTO {
    export type ProviderEnum = 'LOCAL' | 'GOOGLE';
    export const ProviderEnum = {
        LOCAL: 'LOCAL' as ProviderEnum,
        GOOGLE: 'GOOGLE' as ProviderEnum
    };
    export type RoleEnum = 'ADMIN' | 'USER';
    export const RoleEnum = {
        ADMIN: 'ADMIN' as RoleEnum,
        USER: 'USER' as RoleEnum
    };
}