/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UserImageDTO } from './userImageDTO';

export interface UserBasicDTO { 
    id?: string;
    username: string;
    photoProfile?: UserImageDTO;
    reviewsTotalSum?: number;
    reviewsNumber?: number;
    followersNumber?: number;
    followingNumber?: number;
}